services:
  ai-service:
    build:
      context: ../..
      dockerfile: support-services/ai-service/Dockerfile
    container_name: ai-service
    env_file:
      - ./.env.docker
    ports:
      - "8088:8088"
    restart: always
    networks:
      - alpha_network