# Eureka Server là nơi để các service đăng ký và tìm thấy nhau bằng tên thay vì bằng port
# Giúp cho việc giao tiếp giữa các service dễ dàng hơn

server:
  port: 8761 # Port mặc định của Eureka Server

eureka:
  client:
    # Vì đây là Eureka Server, nó không cần tự đăng ký chính nó vào danh sách các service
    register-with-eureka: false
    # Nó cũng không cần tải danh sách các service từ một server khác (vì chính nó là server)
    fetch-registry: false
  server:
    # Thời gian server chờ để đồng bộ hóa dữ liệu nếu registry đang trống (set = 0 để dev cho nhanh)
    wait-time-in-ms-when-sync-empty: 0
    # Tắt chế độ tự bảo vệ để tránh tình trạng service bị đánh dấu là down khi có sự cố mạng hoặc khi service thực sự down (để dev cho nhanh)
    enable-self-preservation: false
    # Khoảng thời gian để server thực hiện việc dọn dẹp các instance đã bị đánh dấu là down
    eviction-interval-timer-in-ms: 5000
