services:
  eureka-server:
    build:
      context: ../..
      dockerfile: infrastructure/eureka-server/Dockerfile
    container_name: eureka-server
    env_file:
      - ./.env
    ports:
      - "8761:8761"
    restart: always
    networks:
      - alpha_network
