services:
  api-gateway:
    build:
      context: ../..
      dockerfile: infrastructure/api-gateway/Dockerfile
    container_name: api-gateway
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    restart: always
    networks:
      - alpha_network
    depends_on:
      - config-server
      - eureka-server
