services:
  cinema-management-service:
    build:
      context: ../..
      dockerfile: core-services/cinema-management-service/Dockerfile
    container_name: cinema-management-service
    env_file:
      - ./.env.docker
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - mysql-db
      - config-server
      - eureka-server
    networks:
      - alpha_network
