name: Deploy Notification Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/support-services/notification-service/**'
      - 'backend/docker-compose.prod.yml' # Chạy lại nếu file compose tổng có cập nhật

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/support-services/notification-service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/notification-service:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Copy docker-compose.prod.yml to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.NOTIFICATION_SERVICE }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY_SUPPORT_SERVICES }}
        source: "backend/docker-compose.prod.yml"
        target: "/home/ubuntu/alpha_cinema"
        
    - name: Deploy Docker Container on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.NOTIFICATION_SERVICE }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY_SUPPORT_SERVICES }}
        script: |
          cd /home/ubuntu/alpha_cinema/backend
          
          # Đăng nhập Docker, dọn rác cũ và kéo image mới
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          
          # Dọn dẹp bản cũ để không tràn RAM con máy micro
          sudo docker compose -f docker-compose.prod.yml stop notification-service || true
          sudo docker compose -f docker-compose.prod.yml rm -f notification-service || true
          sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/notification-service:latest || true
          
          # Kéo bản mới và kích nổ
          sudo docker compose -f docker-compose.prod.yml pull notification-service
          sudo docker compose -f docker-compose.prod.yml up -d notification-service