services:
  user-service:
    build:
      context: ../..
      dockerfile: core-services/user-service/Dockerfile
    container_name: user-service
    env_file:
      - ./.env.docker
    ports:
      - "8086:8086"
    restart: always
    depends_on:
      - mysql-db
      - config-server
      - eureka-server
    networks:
      - alpha_network