server:
  port: 8087 # Port chạy service thông báo

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 6000ms
      connect-timeout: 2000ms
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: "com.movieticket.notification.event.model.OrderSuccessfulEvent"
        spring.json.use.type.headers: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  client:
    service-url:
      # Nơi đăng ký với Eureka Server với tên là notification-service
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

external-services:
  cinema-service:
    base-url: ${CINEMA_SERVICE_BASE_URL}
  product-service:
    base-url: ${PRODUCT_SERVICE_BASE_URL}
